services:
  minio:
    image: coollabsio/minio:latest
    container_name: local-minio
    ports:
      - "9000:9000"   # Puerto para la API de S3
      - "9001:9001"   # Puerto para el panel de administración web
    environment:
      MINIO_ROOT_USER: labinstru
      MINIO_ROOT_PASSWORD: labinstru2026
    command: server /data --console-address ":9001"
    networks:
      - instru_network
    volumes:
      - minio_data:/data
    restart: always
  testinstru:
    image: mysql:latest
    container_name: testinstru
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: testinstru
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - instru_network
    restart: always
  calendar_server:
    image: calendar_server:latest
    container_name: calendar_server
    ports:
      - "4000:4000"
    environment:
      SQL_URL: "mysql://root:testinstru@172.29.72.132:3306"
      EMAIL_PASSWORD: "vusi gvow bzed jvqh"
      PRIMARY_EMAIL_TO: "johnny.chuqui@epn.edu.ec"
      PRIMARY_EMAIL_FROM: "lab.instrumentacion.epn@gmail.com"
      SECUNDARY_EMAIL_TO: "silvana.gamboa@epn.edu.ec"
      SERVICE: "gmail"
      MINIO_IP: "local-minio"
      BUCKET_NAME: "testinstru"
      JWT_SECRET: "d00ceb4e1d182f1327fa150a33243e2507b1d80a60f0870939cd6c2474b3e097d4c8a75a6b51f3b465e2d339a2d2fb413c1cc8385f09128c45505582e661319b"
      APP_URL: "https://172.29.72.132"
      SERVER_DEVICE: "http://172.29.72.132:5000"
      TZ: America/Guayaquil
    networks:
      - instru_network
    restart: always
  device_server:
    image: device_server:latest
    container_name: device_server
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://root:testinstru@testinstru:3306/deviceDB"
      VITE_SERVER_PORT: 5000
      EMAIL_PASSWORD: "vusi gvow bzed jvqh"
      PRIMARY_EMAIL_TO: "johnny.chuqui@epn.edu.ec"
      PRIMARY_EMAIL_FROM: "lab.instrumentacion.epn@gmail.com"
      SERVICE: "gmail"
      TZ: America/Guayaquil
    networks:
      - instru_network
    depends_on:
      - testinstru
    restart: always
  calendar_app:
    image: calendar_app
    ports:
      - "5174:5174"
    networks:
      - instru_network
    restart: always
  home_app:
    image: home_app
    ports:
      - "5176:5176"
    networks:
      - instru_network
    restart: always
  device_app:
    image: device_app
    ports:
      - "5173:5173"
    networks:
      - instru_network
    restart: always
  labinstruapp:
    build: ./deploy
    ports:
      - "443:443"
    networks:
      - instru_network
    restart: always
    volumes:
      - ./deploy/certs:/app/certs:ro

volumes:
  minio_data:
  mysql_data:
networks:
  instru_network: