# version: "3.9"
# services:
#   labinstru:
#     image: mysql
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=labinstru
#   device_server:
#     image: device_server:1
#     ports:
#       - "5000:5000"
#     links:
#       - labinstru
#     depedens_on:
#       device_server:
#         condition: 
#   calendar_server:
#     image: calendar_server:1
#     ports:
#       - "4000:4000"
#     links:
#       - labinstru

services:
  appdevice:
    image: appdevice:latest
    ports:
      - "5173:5173"
  apphome:
    image: apphome:latest
    ports:
      - "5176:5176"

  appticket:
    image: appticket:latest
    ports:
      - "5175:5175"

  appcalendar:
    image: appcalendar:latest
    ports:
      - "5174:5174"
