
GET http://localhost:4000/calendar/getDaysbyMonth/10/2025

###
GET http://127.0.0.1:4000/calendar/getDaysbyWeek/9/2026/21/general

### stefany.villarreal@epn.edu.ec

POST http://172.29.72.183:4000/calendar/NewSession
Content-Type: application/json

{
    "Asunto": "Laboratorio de instrumentación Gr3S2",
    "Hora_inicial": "11:00",
    "Hora_final": "12:00",
    "Periodicidad": "Semanalmente",
    "Responsable": "Alex Oña",
    "Correo_responsable": "alex.ona@epn.edu.ec",
    "fecha_inicio": "2026-10-02",
    "Mesas": "Mesa1,Mesa2,Mesa3",
    "Equipos_usados": "Ninguno",
    "laboratorio": "sensores"
}

### 
DELETE http://172.31.33.25:4000/calendar/DeleteSession
Content-Type: application/json

{
    "Asunto": "Laboratorio de Sensores y transductores GR1",
    "Hora_inicial": "16:00",
    "Correo": "stefany.villarreal@epn.edu.ec"
}

###
POST http://127.0.0.1:4000/calendar/SignUp
Content-Type: application/json

{
    "Nombre": "Alguien",
    "Apellido": "Alguien",
    "Correo": "alguien@epn.edu.ec",
    "Tipo": "Técnico docente",
    "Password": "labRedes"
}

###
POST http://127.0.0.1:4000/calendar/LogIn
Content-Type: application/json

{
    "Correo": "mateo.vasquez@epn.edu.ec",
    "Password": "labRedes"
}

###
DELETE http://127.0.0.1:4000/calendar/DeleteUser
Content-Type: application/json

{
    "Correo": "alguien@epn.edu.ec",
    "Password": "labRedes"
}

###
POST http://172.31.33.28:4000/calendar/OpenTicket
Content-Type: application/json

{
    "Asunto": "Falla en el proyector",
    "Descripcion": "El proyector no enciende",
    "Prioridad": "Alta",
    "Solicitante": "Mateo Vásquez",
    "Correo_solicitante": "mateo.vasquez@epn.edu.ec"
}

###
POST http://172.31.33.28:4000/calendar/CloseTicket
Content-Type: multipart/form-data;

###
GET http://172.31.33.28:4000/calendar/GetNewTickets

###
GET http://172.31.33.28:4000/calendar/GetClosedTickets

###
GET http://127.0.0.1:4000/calendar/GetTicketImage/9GdpOcJel5mpEYoY6z2Ik
###
GET http://127.0.0.1:4000/calendar/regDevice/1/general

